# Generated by Django 2.1.5 on 2019-01-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeDoProduto', models.CharField(max_length=32)),
                ('estoqueMinimo', models.IntegerField()),
                ('estoqueAtual', models.IntegerField()),
                ('precoDoProduto', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
