# Generated by Django 2.1.5 on 2019-02-04 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagProduto', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='CodigoProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeDoProduto', models.CharField(max_length=32, verbose_name='Nome do Produto')),
                ('estoqueMinimo', models.IntegerField(verbose_name='Estoque Mínimo')),
                ('qtdProdutos', models.IntegerField(verbose_name='Quantidade de Produtos')),
                ('precoDoProduto', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Preço')),
                ('categoria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='produtos.Categoria')),
                ('codigoDoProduto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='produtos.CodigoProduto')),
            ],
        ),
    ]
